<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loader</name>
   <tag></tag>
   <elementGuidId>b58d5f75-f87d-45a9-b5da-c567573789c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31e51f0e-bdc2-4f49-b85c-abd6f82ce32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader</value>
      <webElementGuid>ab245a28-e568-4ddb-97c4-353c338b2950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@id=&quot;pega_ui_load&quot;]/div[@class=&quot;throbber&quot;]/div[@class=&quot;loader&quot;]</value>
      <webElementGuid>ed96d6ed-dd2d-4041-b81c-eb8adb8570d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
