<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ready_TrialDetails_D_GetMyTrials.pxResult_b693e1</name>
   <tag></tag>
   <elementGuidId>c61cbd5f-f9a7-446b-9d89-f2805cc168bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='RULE_KEY']/div/div[2]/div/div[4]/div/div[2]/div/div/span/i)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i[name=&quot;TrialDetails_D_GetMyTrials.pxResults(1)_175&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'TrialDetails_D_GetMyTrials')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7b4ceee3-3f0d-468a-9afc-e23dcb12527b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;showMenu&quot;,[{&quot;dataSource&quot;:&quot;TrialActions&quot;, &quot;isNavNLDeferLoaded&quot;:&quot;false&quot;, &quot;isNavTypeCustom&quot;:&quot;false&quot;, &quot;className&quot;:&quot;MyPega-Data-MyTrials-Trial&quot;,&quot;UITemplatingStatus&quot;:&quot;Y&quot;,&quot;menuAlign&quot;:&quot;left&quot;,&quot;format&quot;:&quot;menu-format-standard&quot; , &quot;loadBehavior&quot;:&quot;ondisplay&quot;, &quot;ellipsisAfter&quot;:&quot;999&quot;,&quot;usingPage&quot;:&quot;D_GetMyTrials.pxResults(1)&quot;, &quot;useNewMenu&quot;:&quot;true&quot;, &quot;isMobile&quot;:&quot;false&quot;, &quot;navPageName&quot;:&quot;pyNavigation1694785157687&quot;},&quot;:event&quot;]]]</value>
      <webElementGuid>46ce650a-68a6-49b2-8a7e-aa56e2e7d590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Icon</value>
      <webElementGuid>0dfd3caa-8ad9-4bb3-bb7c-f80324f229e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icons pi pi-dot-3-alt-solid</value>
      <webElementGuid>6722a54d-9b46-401f-a4c7-304efda7393b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TrialDetails_D_GetMyTrials</value>
      <webElementGuid>afad2d1c-7fcc-4825-b542-104e190a349c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>1019d37c-1a8d-4657-a27e-751249d43a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1e1fe6f9-9462-4aa3-ac2e-def10d09c18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>2e87b7a8-a438-45db-a979-3c0bbef8aec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db511d47-3cb4-48d0-a4c4-5ef6d67b1dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e2eb71c7-bb0f-4bcc-9947-8ed10b384319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l2&quot;)/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-layout item-2 remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@class=&quot;rdlWrapperDiv&quot;]/div[@class=&quot;content    flex  layout-content-inline_grid_triple content-inline_grid_triple environments-list&quot;]/div[@class=&quot;content-item content-sub_section item-1 flex flex-row&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-mobile_card&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle pointer has-action auto-width-column nowrap width-100-pct flex-1-item-2&quot;]/div[@class=&quot;content-item content-layout item-2 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  margin-l-2x padding-r-1x padding-t-1x&quot;]/div[@class=&quot;content-item content-layout item-4 remove-top-spacing remove-bottom-spacing remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  padding-t-2x collab-details margin-t-1x&quot;]/div[@class=&quot;content-item content-layout item-2 remove-top-spacing remove-bottom-spacing remove-right-spacing align-end flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row circle-bg-icon dataValueWrite&quot;]/span[1]/i[@class=&quot;icons pi pi-dot-3-alt-solid&quot;]</value>
      <webElementGuid>a618b538-cad4-4dfe-b9dd-b39ec4c4069b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@name='TrialDetails_D_GetMyTrials.pxResults(1)_175']</value>
      <webElementGuid>e95cae94-6918-4347-acad-e0dca46c8aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div[2]/div/div[4]/div/div[2]/div/div/span/i</value>
      <webElementGuid>616e9244-0d81-4806-876c-26653be481c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready'])[1]/following::i[1]</value>
      <webElementGuid>50ec4c33-6053-4e30-b18f-4a3742488740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community Edition'])[1]/following::i[1]</value>
      <webElementGuid>27cdd816-35ec-4cf2-8dff-cdffca9547d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPIRES DEC 03, 2023'])[2]/preceding::i[2]</value>
      <webElementGuid>e5306d63-303f-44b9-af5c-61dd1808c6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Owner'])[2]/preceding::i[4]</value>
      <webElementGuid>d9ad7abf-e853-420b-a31f-f8b1a34a3f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/span/i</value>
      <webElementGuid>5faeefac-dc03-4c71-b717-dc2c5333fa5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@name = 'TrialDetails_D_GetMyTrials.pxResults(1)_175']</value>
      <webElementGuid>08a3a9d2-a4d3-4e69-86a2-2d2dffa412ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
