<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_credentials.passcode</name>
   <tag></tag>
   <elementGuidId>abaec146-2ecc-495d-adcc-8a7161204119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input63']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input63</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac47cfea-21c5-4d08-bc96-e5f92ac999d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4e719b62-0a68-41b9-b4fd-630f252c5a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credentials.passcode</value>
      <webElementGuid>b31a40f9-78c3-4573-9957-3396abb2e68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input63</value>
      <webElementGuid>7b4c35bf-bcdb-4b8a-ad00-f8c1368db2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bee48e91-d7d7-444a-9972-e62762c5f588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-with-toggle</value>
      <webElementGuid>91112774-943b-4558-aa67-983f4553e6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input63&quot;)</value>
      <webElementGuid>3fb04094-80b2-400b-a031-73f4e525c635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input63']</value>
      <webElementGuid>0a1d0787-1261-49d9-895a-c9d3938a2199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form55']/div/div[4]/div/div[2]/span/input</value>
      <webElementGuid>c89151c8-3ba2-4a40-a8ba-9482b39777bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d60c51f-36d3-4f9f-9470-a547a617e16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'credentials.passcode' and @id = 'input63']</value>
      <webElementGuid>c7935009-fd2f-4d77-8e48-c136d847cc1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
