<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Case Types</name>
   <tag></tag>
   <elementGuidId>4352c15d-9404-4442-b86a-04ff351b9512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Case Types')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa18437739661209pz.pxResults(2)_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c26323c-e4f8-4c75-b11d-bbebad429a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>express-tab-cases</value>
      <webElementGuid>d2e46bed-1abf-45dc-bc1c-10746d2a45ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9bc8eea8-4224-4ee3-bb75-077280bf39f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>44ecad97-b6bc-4cdd-b712-a75757719e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>f08b9ceb-0c0e-4d5c-815f-4c49a67678e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa18437739661209pz.pxResults(2)_1</value>
      <webElementGuid>bf7e6bc9-0cf8-4f76-83dc-0841557c4266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Case Types</value>
      <webElementGuid>e8e16b24-c788-438d-8c7c-0590ab9d5fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Header_nav</value>
      <webElementGuid>d4e342bc-39bd-4bb6-a947-703afdb7277b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Case Types</value>
      <webElementGuid>130f7709-0c21-4e5c-a652-eb2f820fcde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_pxExtensions_Requestor_ReadOnly_pa18437739661209pz$ppxResults$l2&quot;)/td[@class=&quot;gridCell    gridCellSelected&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none set-width-auto has-action&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  set-width-auto pointer  layout-content-inline content-inline  clearfix&quot;]/div[@class=&quot;content-item content-field item-1 remove-left-spacing remove-right-spacing    no-menu icon-tile centered&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueRead&quot;]/span[1]/a[@class=&quot;Header_nav&quot;]</value>
      <webElementGuid>6d9a79a1-1c0f-4562-a448-aa1d28bdfcfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa18437739661209pz.pxResults(2)_1']</value>
      <webElementGuid>a8511aec-d014-4406-9481-5197910723ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/span/a)[9]</value>
      <webElementGuid>0278a281-684f-42c0-9175-9d06edab40f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Case Types')]</value>
      <webElementGuid>1d373a82-a22a-432d-82b4-1bff13e146af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prediction Studio'])[1]/following::a[2]</value>
      <webElementGuid>dc10e742-40ed-4cc6-9dfa-5bdd95b17370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dev Studio'])[1]/following::a[3]</value>
      <webElementGuid>b3ad0413-eeb4-4747-b98b-598bfaa5bc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MK'])[1]/preceding::a[8]</value>
      <webElementGuid>5b17f265-30b7-411d-83c7-8cf3a0d189aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode'])[1]/preceding::a[8]</value>
      <webElementGuid>cc2077a6-7673-48f9-b95c-ac53a3a5d7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Case Types']/parent::*</value>
      <webElementGuid>8e6b1ef3-8551-4272-ae15-525f9ab3d69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[16]</value>
      <webElementGuid>ba678132-0d41-4344-bb79-4f8e2244a688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/div/div/div/div/div/span/a</value>
      <webElementGuid>3b910661-42aa-4208-8712-d101c5595521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa18437739661209pz.pxResults(2)_1' and @title = 'Case Types' and (text() = 'Case Types' or . = 'Case Types')]</value>
      <webElementGuid>f33a09d3-ecec-445f-a25d-9377e083c833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
