<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Data</name>
   <tag></tag>
   <elementGuidId>be5a9486-9d08-4187-be8f-e371d071618b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa3482104599507pz.pxResults(3)_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Data')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4059497-5f27-42db-b845-234b33683cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>express-explorer-data</value>
      <webElementGuid>04f8d11f-2ff0-4e98-a088-4ef9a6ecff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>93d4764d-1c14-4ac8-b567-e19fd31d7012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>cf007edd-0a45-4816-96d0-d5b1c1480d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>a2686a37-bd33-4382-bebf-e185c40cd450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa3482104599507pz.pxResults(3)_1</value>
      <webElementGuid>4490042b-9025-470c-8724-8df4e157f214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Data</value>
      <webElementGuid>8af60d1c-6d0d-454e-858c-dff6600300f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Header_nav</value>
      <webElementGuid>49729746-774a-43c0-8da0-e1d911546561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data</value>
      <webElementGuid>cbfddb73-b024-4d54-9dec-3046373da401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_pxExtensions_Requestor_ReadOnly_pa3482104599507pz$ppxResults$l3&quot;)/td[@class=&quot;gridCell&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none set-width-auto has-action&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  set-width-auto pointer  layout-content-inline content-inline  clearfix&quot;]/div[@class=&quot;content-item content-field item-1 remove-left-spacing remove-right-spacing    no-menu icon-tile centered&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueRead&quot;]/span[1]/a[@class=&quot;Header_nav&quot;]</value>
      <webElementGuid>4b026d4c-48c6-4fbd-9c6e-3a1f2afc94f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa3482104599507pz.pxResults(3)_1']</value>
      <webElementGuid>6baf9036-9657-42b2-87c9-f9f39a2e17ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/span/a)[10]</value>
      <webElementGuid>095e8950-49f3-4c53-9da9-a8cc2b0ee237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Data')]</value>
      <webElementGuid>34b7254a-0c04-454e-81fb-371388bda65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prediction Studio'])[1]/following::a[3]</value>
      <webElementGuid>c8838bd8-cc3c-4040-bbf4-1b5e16e94e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dev Studio'])[1]/following::a[4]</value>
      <webElementGuid>be8c3462-6c97-4013-a2ee-e2996650ed12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MK'])[1]/preceding::a[7]</value>
      <webElementGuid>cfc893d4-53dc-4efa-9733-ee92b472b626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode'])[1]/preceding::a[7]</value>
      <webElementGuid>7f0976cb-8af5-43ad-830d-e1ec1c6cb333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data']/parent::*</value>
      <webElementGuid>7e67f1cd-9ef1-4084-8ee3-5cf2c4b38c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>c791d826-ed05-47ad-910c-32425692b1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/div/div/div/div/div/span/a</value>
      <webElementGuid>d3ff8bbb-4946-41fb-a537-1246d2ec22da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pyExpressExplorerTabs_D_pxExtensions_Requestor_ReadOnly_pa3482104599507pz.pxResults(3)_1' and @title = 'Data' and (text() = 'Data' or . = 'Data')]</value>
      <webElementGuid>8225d20f-be97-4f81-93c5-53538ea32b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
