<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FORM STEP</name>
   <tag></tag>
   <elementGuidId>a5d7f11a-ee7d-49d6-a7c1-660745092008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzDisplayAddStep_CaseTypeStages.pyStages(1).pyProcesses(1)_4&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='pzDisplayAddStep_CaseTypeStages.pyStages(1).pyProcesses(1)_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b91bff8d-9059-46b2-92c1-6d5ec2ee8785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20160330120150930070043098528494344055097412168</value>
      <webElementGuid>ddcb6734-f2e6-4278-8cd2-2ada7bb6ee0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>225bc3c9-7303-442a-83ba-fa026188ed69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>0831afe0-7f50-4325-9c24-78257d3bd044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>831a74b6-ff99-4b5b-9eef-82e96a051e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzDisplayAddStep_CaseTypeStages.pyStages(1).pyProcesses(1)_4</value>
      <webElementGuid>6b060eae-3393-4e1c-a2f1-5fa9780e1fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzDisplayCaseTypeLifeCycle&quot;, &quot;pzDoStepPaletteAction&quot;, &quot;ProcessContextReference=#~CaseTypeStages.pyStages(1).pyProcesses(1).pxPageReference~#&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4OTMzYWE2MWFiNzZhMmMxNjUxZjlmMjQxMTMzMWJkYWVkMDgwNjBjYzc2MjczNjAzYjA2ZTljYmViYzE2MTA0NjViZTM0Y2JlMDY5NTRlZTYxZTk0NGUwNjhkNjZkMzkxYTg5NDBkNDQzMjYwZjAyYzZiZjI4NDExMTJhYTQ0MjgyYzc4NDQzNjQwYTQzZDI4YzJjYjI3M2RmN2RhMTAzOTE1ODFjMzg4ZjcxNGM0OWYyOWU3NmE1ZWNkNjk1MjhhNDc1YWY2MDljM2RmMzc5Yjc2NzczNDM0YWEwOTUzNTI4M2IxZjcwYmZkOTg3YTMxZTZjYThlMDkwYjYyYTY1MQ%3D%3D*&quot;,{&quot;Action&quot;:&quot;AddShape&quot;,&quot;ShapeType&quot;:&quot;single&quot;},{}],&quot;CaseTypeStages.pyStages(1).pyProcesses(1)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzDisplayCaseDesignerProperties&quot;, &quot;pxValidateContext&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4ZTgyNjU0YjFjMmYxYTMwNDZjZjc0OTZiN2RiYTRkMDI5M2I1MjhkYWJjMjQ5YWY0OTM1YmI2OWI1ZDQ4ZjE1ODlhNDY1NDg2ZWZhMzI0YTAyZTIxOTc0OTk5NDlkNzFiOGI1NzJmYzAxMTdkZmUzN2I0YTE3YzZmOWFmMGM5YjkwYjUzNGY4OWVkNDlhNzVmNGUyN2NkY2YyMzQ2NWQwNg%3D%3D*&quot;,{&quot;Context&quot;:&quot;&quot;},{}],&quot;CaseTypeStages.pyStages(1).pyProcesses(1)&quot;]],[&quot;runScript&quot;, [&quot;handleNavigationOfStepPalette(\&quot;\&quot;)&quot;]]]</value>
      <webElementGuid>7ae42fc0-01d2-4cb6-9a26-bcd3016c01c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add step to the process</value>
      <webElementGuid>f531f249-abd3-4996-9071-ce92f1b77f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FORM STEP</value>
      <webElementGuid>b974b44a-cf77-4a08-9ebf-2ef17d3740b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID2&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;content  layout-content-stacked content-stacked&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  layout-content-simple_list content-simple_list  clearfix&quot;]/div[@class=&quot;content-item content-field item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/a[1]</value>
      <webElementGuid>25b9c98c-b547-4143-a212-e26b41629ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pzDisplayAddStep_CaseTypeStages.pyStages(1).pyProcesses(1)_4']</value>
      <webElementGuid>a39ac868-2adb-4a2d-b8a5-f5d7c02f5d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div/div/div/div/span/a)[3]</value>
      <webElementGuid>55cdeffa-9e85-4251-a2c6-c1a2731a7038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FORM STEP')]</value>
      <webElementGuid>5e51e590-3932-4e01-8651-91cd832dc1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/following::a[3]</value>
      <webElementGuid>14066262-0f54-45f7-86a9-8cf4d157157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Input'])[1]/following::a[3]</value>
      <webElementGuid>b913a4d1-6835-4f29-a38b-c2deab6033a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No actions'])[1]/preceding::a[1]</value>
      <webElementGuid>64cfaf18-6990-4e32-acad-866a7258c735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No processes'])[1]/preceding::a[1]</value>
      <webElementGuid>381427e5-89bc-46cd-b193-07a27691a9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FORM STEP']/parent::*</value>
      <webElementGuid>312bbb78-64d3-42b6-b5b2-f88c4f4bf91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[28]</value>
      <webElementGuid>bce6cba0-7945-404b-9580-0bb74f49e4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div/div/div/div/div/div/div/div/span/a</value>
      <webElementGuid>32f3b947-8d8d-4d2b-bc31-6d06fc255c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pzDisplayAddStep_CaseTypeStages.pyStages(1).pyProcesses(1)_4' and @title = 'Add step to the process' and (text() = 'FORM STEP' or . = 'FORM STEP')]</value>
      <webElementGuid>46473d1d-9889-4f14-a246-d5ac626d7fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
