<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_STAGE</name>
   <tag></tag>
   <elementGuidId>c4cc6709-b126-4c34-84cd-b0f8b17f93c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzDisplayAddStage_CaseTypeStages_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='pzDisplayAddStage_CaseTypeStages_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa283f5b-f9df-4f65-b3d4-9da9862fcb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014112606300305021366</value>
      <webElementGuid>2efb45c1-662e-41cf-b85c-b675d1be9d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>539f46ae-671a-407d-8c0f-2783af374ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>bb91bd21-1fc7-478c-87e7-ae2b87417ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>f2a8373f-1a3f-40fe-983d-2bbb96ad0e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzDisplayAddStage_CaseTypeStages_1</value>
      <webElementGuid>95a73f1e-b0b1-474f-878d-a1e5a10353f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzStagesWrapper&quot;, &quot;pxAddPrimaryStage&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4OWM1YTc3YTc0OTljN2FjMjBmMTI2N2Q2MDc0Y2IzOWNlYjM3Mzg4YzcwOGU5MmVkNmRiOWMwN2Q3YjliYjBiYTZiMmRhNTViMTI5Y2RiNDg5NTg4NTY4NjE1MzU4OTkxZWEwYjM1NjUzNWU0OWYzNTNhZGNhYWExMjM3MThmZDhjM2RmZDU0MWQ2ZWZiOGU3YjkzNWRmMDQ2YzNiYzgzZDdkZmJkOWMxZmJmODk2MjFjM2IxMzQyODNkMjk0YjIyZDVlZDRhN2QxZDA5ZGViYjMxYTRiODVhNmY3ODU3Y2I%3D*&quot;,{&quot;stageName&quot;:&quot;&quot;,&quot;stageIndex&quot;:&quot;&quot;},{}],&quot;CaseTypeStages&quot;],[&quot;|&quot;,[&quot;OP&quot;,[&quot;$PCaseTypeStages$ppzShowLifeCycleStagesOnly&quot;,&quot;!=&quot;,&quot;false&quot;,&quot;true&quot;]]]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzOptionalActionsWrapper&quot;, &quot;pxAddPrimaryStage&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4OWM1YTc3YTc0OTljN2FjMjBmMTI2N2Q2MDc0Y2IzOWNlYjM3Mzg4YzcwOGU5MmVkNmRiOWMwN2Q3YjliYjBiYTZiMmRhNTViMTI5Y2RiNDg5NTg4NTY4NjE1MzU4OTkxZWEwYjM1NjUzNWU0OWYzNTNhZGNhYWExMjM3MThmZDhjM2RmZDU0MWQ2ZWZiOGU3YjkzNWRmMDQ2YzNiYzgzZDdkZmJkOWMxZmJmODk2MjFjM2IxMzQyODNkMjk0YjIyZDVlZDRhN2QxZDA5ZGViYjMxYTRiODVhNmY3ODU3Y2I%3D*&quot;,{&quot;stageName&quot;:&quot;&quot;,&quot;stageIndex&quot;:&quot;&quot;},{}],&quot;CaseTypeStages&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PCaseTypeStages$ppzShowLifeCycleStagesOnly&quot;,&quot;=&quot;,&quot;false&quot;,&quot;false&quot;]]]],[&quot;runScript&quot;, [&quot;pega.cd.setDirtyState()&quot;]]]</value>
      <webElementGuid>c8174034-6c6f-418d-af22-95c6efd3a00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add stage to case type</value>
      <webElementGuid>f653e0ca-fe61-44c5-bafb-03f53ae0358a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STAGE</value>
      <webElementGuid>f051b203-9957-46d5-969a-2275785a6e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section8422&quot;)/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default content-default two-col-main-sidebar two-col-main-sidebar_full_height_sidebar clearfix modal-default lifecycle-column-container&quot;]/div[@class=&quot;content-item content-layout item-1 column-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-stacked  content-stacked clearfix&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-bottom-spacing remove-right-spacing remove-top-spacing remove-left-spacing&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  stagesAndProcessesWrapper&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default CanvasScrollLayout&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/ul[@id=&quot;stages&quot;]/li[@class=&quot;stage addNewStage&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@id=&quot;CT&quot;]/div[@class=&quot;layout layout-none set-width-auto&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;content  set-width-auto layout-content-simple_inline content-simple_inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-all-spacing    add-stage&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/a[1]</value>
      <webElementGuid>9f335401-036f-4eca-8f76-0a754537a019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pzDisplayAddStage_CaseTypeStages_1']</value>
      <webElementGuid>9c1e0071-8664-437f-b75e-d8383145cc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CT']/div/div/div/div/div/div/span/a</value>
      <webElementGuid>81d021e5-36b0-4acd-a1bb-a01f29305b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'STAGE')]</value>
      <webElementGuid>c009931f-4c88-4565-93a1-c47729a1bc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No processes'])[1]/following::a[2]</value>
      <webElementGuid>0c62f626-0844-44de-afa0-3d3ff242611b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No actions'])[1]/following::a[2]</value>
      <webElementGuid>7f31eca3-ae22-41ed-bf3e-1c58bc415736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personas &amp; Channels'])[1]/preceding::a[2]</value>
      <webElementGuid>2815cebb-ae8b-42a1-9da9-cfe75080d79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[1]/preceding::a[2]</value>
      <webElementGuid>9ac65a7f-196f-4908-8bb6-8589bc752a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='STAGE']/parent::*</value>
      <webElementGuid>b607f6df-66ed-4815-9af1-4f4d7726091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[31]</value>
      <webElementGuid>ea0ad7cb-1c5c-4124-a32f-075d28f2127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div/div/div/div/span/a</value>
      <webElementGuid>900e06f6-5925-4d0a-b2fa-ee2ccea6daf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pzDisplayAddStage_CaseTypeStages_1' and @title = 'Add stage to case type' and (text() = 'STAGE' or . = 'STAGE')]</value>
      <webElementGuid>00df3e44-d955-4a2e-a161-155341542467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
