<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_1</name>
   <tag></tag>
   <elementGuidId>c3791343-4145-470e-ba6d-65537f120e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pyExpressLPDoneSection_pyDisplayHarness_8&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pyExpressLPDoneSection_pyDisplayHarness_8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87b6ca5b-6650-4150-945d-78f32537bfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20181012021634084217185</value>
      <webElementGuid>36412730-c80f-4c55-9b49-46dd788ad93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;pzToggleDataTypeSaveLabel&quot;, &quot;=&quot;, &quot;pyDisplayHarness&quot;,&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;pzClearDataList&quot;, &quot;=&quot;, &quot;pyDisplayHarness&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzEditableHeader&quot;, &quot;pzSaveDataTypeWrapper&quot;, &quot;dataObjectID=#~D_pzManageDataObject.pyPurpose~#&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4OGU0MzBhN2FkNWY5Zjg4NjdkMzdlNjFiNDQyNGVkNDZlNzNjMGU5YjI1OWEzYjVjMGJhZmM4YWNkOTEwYWRlMWZiNzE3MTQ1OTFlYWExN2RhNjM5MzM3ZmU5NTljMDYxYTU4ZjM2NGZlODExYzU0YjU3Y2FmZTE4ODYzYTUzOWI4OTZlYWU5NzVlYzAzMDA4Y2EwYTNjZDEwY2JkM2M5YjY5OGQwYTJmNDA3MDliOWU4OWFkYTFiYTRhZTdiYjkwOTQ4NDYwZmY1MGEwYzdmYzgyZmRmMTRmZWE0OTk5YTJlYWIxOWE2NmYyYjkyZGM3N2ZhNGE1OTk4OGQxOTNhOGY0MDc0NzE4ZDRmOTNhNzA1NWY1N2Y0M2ExMzM0MzI4*&quot;,{&quot;onDone&quot;:&quot;&quot;,&quot;isNew&quot;:&quot;&quot;,&quot;nonPegatable&quot;:&quot;true&quot;},{}],&quot;pyDisplayHarness&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzDataTypeProperties&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmVjMzA3N2MzY2ZkODk2YzVkY2UxZTZmMzVkZWEzOTBk*&quot;,{},{}],&quot;pyDisplayHarness&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyDisplayHarness&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTQzMDI2ZDgzN2ZlZDA5MTcyMWQ2ZjU1MTMyMDU4MjEwMGQ2MzM5NTYxM2ZmZTM3OTk5OGM3NmU1OGRmNWYzNjc4MDQxYTI0MDA2ZTg0OGVmZGFkYjZmNTE2MTJmYzBhN2U1NjAxNWI3ZjE3NGU1MWNkMWY0MzQ3MWNhNGQ4NTExZWEwMDZmY2FiNDZmZDExNzI1NzZiYzg3MTc0YmNhYzcwNDE0YTgzYzE0OWE1NGZhOTMwNGI1ODBlNDRmNDM1ZDNmNjU0NDIwMjU5MTM4NmQ1MDQ0NjY4M2M2MDI3NmE1ZDlkZTQzY2VkNDIzNjU2ODMzYjc0MGVkNGI0MTRiZjQ%3D*&quot;]],[&quot;runDataTransform&quot;, [&quot;pzToggleDataTypeSavingLabel&quot;, &quot;=&quot;, &quot;pyDisplayHarness&quot;,&quot;:event&quot;]],[&quot;runScript&quot;, [&quot;pega.collaboration.actions.updateCollaboration(\&quot;#~pyDisplayHarness.pyCollaborationHandleForData~#\&quot;,\&quot;save\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;pega.u.d.clearReloadedStatus()&quot;]],[&quot;runScript&quot;, [&quot;pega.u.d.clearDirtyState()&quot;]]]</value>
      <webElementGuid>cad43900-cf71-46f8-ba3e-48cebfbed732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyExpressLPDoneSection_pyDisplayHarness_8</value>
      <webElementGuid>2cfac69b-c09d-48b5-af00-c607dec10a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>edd408cc-70da-487a-af1d-7ff2869c5b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24f2b3e1-0265-4ff6-a147-1aeb01cdc261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1ff5426e-f63d-4f7a-b608-d263965a58b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/header[@class=&quot;workarea-view-header workarea-view-header-fixed&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  flex-grow-1-item-2 layout-box-shadow&quot;]/div[@class=&quot;content-item content-sub_section item-3 flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none  float-right set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-field item-2 flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>0bd7c156-5a1d-4d22-abff-aec95d9f1c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pyExpressLPDoneSection_pyDisplayHarness_8']</value>
      <webElementGuid>d86e98e9-897c-4ad2-8bfe-5b002fef5ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div[2]/span/button</value>
      <webElementGuid>0f0617a0-3c9b-4415-9657-2998b8490fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data object:'])[1]/following::button[1]</value>
      <webElementGuid>751aebe6-6fe8-4a20-9d2a-a23cb44ae360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::button[2]</value>
      <webElementGuid>81920da5-50cd-43c5-82d6-0a6dd81ceceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data model'])[1]/preceding::button[1]</value>
      <webElementGuid>db698512-3dff-4985-9bf4-dc2c14076875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data model'])[2]/preceding::button[1]</value>
      <webElementGuid>ad8c1423-f674-4181-a230-90f193f71070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/button</value>
      <webElementGuid>2ccdef8f-7a95-4728-8a0e-d8736bc69798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pyExpressLPDoneSection_pyDisplayHarness_8' and @type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>119e459c-0bbc-4aac-b3cd-1646d8d05e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
