<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next2</name>
   <tag></tag>
   <elementGuidId>8db0f51a-8b7b-4894-89ad-b6bc2dda8011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzModalNextButton_pyWorkPage_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//*[@class='buttonTdButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc75d8d1-39dc-42d8-bcb1-ca9b509017dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202003240614170687236</value>
      <webElementGuid>2548feb1-93a1-4e83-b417-2fe008dcecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzEnterCaseTypeInformation&quot;, &quot;pzValidateCaseTypeInfoWrapper&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzLyRGbG93TW9kYWxQcm9jZXNzfWQ0ZGUwZmY0ZTdhZjZlY2NkMjMwZTAxMmE4NjZjNTJkODlmZWRmMTY3MjU4ZWRkZDE2OWUyMDAyNmU1MmM0MWY2NTFhMzllMjNlODNhNDE3NDZlZDE3MmZkMjFhZDAwOWE2Y2M2YTFjYTE2MDYxOGI0MjA3YmEyODVkMTY2ZTQwYzFhMGJhNmNiNmFmY2JiNTAwY2YwZjJjMjRjZWE5NzAxM2ZiN2Y1NWRlYmVmMWQwNDc4YWI1YWQ4ZWYzNTA4ZDIxOGNhYjVlNDk2ZDdmNzA3ZGNjYzg2NWM1ZjdjMzVj*&quot;,{},{}],&quot;pyWorkPage&quot;]],[&quot;runScript&quot;, [&quot;pega.p.doClearActions(\&quot;#~NewCaseTypeStages.pyDoClearActions~#\&quot;)&quot;]],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;setUserStart&quot;,[&quot;FINISHASSIGNMENT&quot;]],[&quot;doFormSubmit&quot;,[&quot;pyActivity=FinishAssignment&quot;,&quot;:this&quot;,&quot;&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>ec333bf5-0f39-4f2d-bb2e-8773bbb50ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzModalNextButton_pyWorkPage_2</value>
      <webElementGuid>00bb26b9-6a06-4474-a195-c1c27fcbefa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>691effc6-bfd5-4e53-a545-38b18e37ce66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>381647cd-41c2-4191-b2c3-2a72e9e15b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next   </value>
      <webElementGuid>8e64215b-fd7d-4aa1-b6ee-dc82ee99377a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalContent&quot;)/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  set-width-auto margin-0&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto margin-r-0&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-right-spacing flex flex-row margin-r-0&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-mimic_a_sentence  content-mimic_a_sentence clearfix&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>007f75ad-6a84-49cf-9505-6effdd8d0e13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzModalNextButton_pyWorkPage_2']</value>
      <webElementGuid>47d0ecc5-b30d-4ad7-befc-05e30f543673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div[2]/div/div/span/button)[5]</value>
      <webElementGuid>41eb8fd2-af92-459c-9668-b41776bc2534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[1]</value>
      <webElementGuid>82851aca-cd86-493a-bea5-cdb84a0b86a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[2]</value>
      <webElementGuid>f66f9eb4-acc9-4664-a0a6-ebdee100b8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsaved changes'])[1]/preceding::button[1]</value>
      <webElementGuid>a4c96bc6-b522-473b-b0dc-6d0ed257aa1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are about to discard your unsaved changes.'])[1]/preceding::button[2]</value>
      <webElementGuid>5a5829d3-54af-4414-b9c3-06b84033799c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/span/button</value>
      <webElementGuid>b50878fb-6682-4866-8a07-597c37f31766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzModalNextButton_pyWorkPage_2' and @type = 'button' and (text() = 'Next   ' or . = 'Next   ')]</value>
      <webElementGuid>b5662a28-c6db-43c1-b7b8-5b8c4776a3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
