<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>a92f8763-6882-4c47-86ce-d186cbdbcc6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content-item.content-field.item-4.flex.flex-row.margin-r-0.dataValueWrite > table.buttonMainTable.Strong > tbody > tr > td.buttonTdMiddle > #submitButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='submitButton'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>416bb684-e5b7-445c-be5c-f82336d8fa87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonTdButton</value>
      <webElementGuid>63135951-2027-4c56-a4f0-dd02e1f4c53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pega_version</name>
      <type>Main</type>
      <value>HTMLPROPERTY</value>
      <webElementGuid>6f7f52b6-7c6d-4f4c-a13e-050fdf772b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>ea015f4f-ee3a-424f-9370-eb48ae0ea3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(typeof(pega) !='undefined' &amp;&amp; pega.u.d) setUserStart(); doFormSubmit('pyActivity=FinishAssignment',this,'Submitting...',event); </value>
      <webElementGuid>ca36bc71-d2b8-46e5-99ce-6a8c7151ed68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74ccb238-a7b3-4b7e-85a1-7358aafb76f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Complete this assignment</value>
      <webElementGuid>59a1450a-9b52-467e-96b7-965c8104be15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Complete this assignment</value>
      <webElementGuid>6f90e094-49d5-4678-9545-91fef86e07b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>non-auto</value>
      <webElementGuid>b773afab-9ddf-465d-b5f4-73437fde27b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Submit </value>
      <webElementGuid>f9faf348-019c-4701-b5b4-dd215dd27b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalContent&quot;)/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-simple_list  content-simple_list&quot;]/div[@class=&quot;content-item content-layout item-3 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-modal_button_array&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-2 align-end set-width-auto flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto auto-width-column&quot;]/div[@class=&quot;content-item content-field item-4 flex flex-row margin-r-0 dataValueWrite&quot;]/table[@class=&quot;buttonMainTable Strong&quot;]/tbody[1]/tr[1]/td[@class=&quot;buttonTdMiddle&quot;]/button[@id=&quot;submitButton&quot;]</value>
      <webElementGuid>748ce056-55a0-4103-ac11-b82dea3eb5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='submitButton'])[2]</value>
      <webElementGuid>f38936f0-6732-42d6-85c6-ece89be1c0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div[2]/div/div[4]/table/tbody/tr/td[2]/button</value>
      <webElementGuid>8fcd645e-0c34-41db-a583-c18bad58500f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[1]</value>
      <webElementGuid>e7221dd6-2eda-4f19-94c5-a4ddca0dd7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add sample request'])[1]/following::button[2]</value>
      <webElementGuid>71ccc9a2-5a85-4576-892f-92ee46837e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsaved changes'])[1]/preceding::button[1]</value>
      <webElementGuid>3c3ac025-acd0-4df0-abe3-2e8f6a8a3365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are about to discard your unsaved changes.'])[1]/preceding::button[2]</value>
      <webElementGuid>43cd4bb1-ff88-427e-9092-1b58d8dbd1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>b689f837-a987-419e-9d75-6478a02610f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[2]/button</value>
      <webElementGuid>2dcd1424-f22e-4666-b781-42caab220944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submitButton' and @type = 'button' and @title = 'Complete this assignment' and @alt = 'Complete this assignment' and (text() = '  Submit ' or . = '  Submit ')]</value>
      <webElementGuid>0613be85-5045-48e2-add0-e2143bebdce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
