<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>7aa6dff4-b34d-409d-a7cd-4dfb605f104e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzDeleteCaseTypeWarnMessage_D_pzExplorerCaseTypes.pxResults(1)_6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pzDeleteCaseTypeWarnMessage_D_pzExplorerCaseTypes.pxResults(1)_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2befa689-783d-499e-a33d-ce4e5016894f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201503171638260869104993</value>
      <webElementGuid>4a4667bc-dda2-4f9a-9965-69f429dec954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;closeContainer&quot;,[&quot;:event&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;ClassName=#~D_pzExplorerCaseTypes.pxResults(1).pyClassName~#&quot;, &quot;D_pzExplorerCaseTypes.pxResults(1)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTQzMDI2ZDgzN2ZlZDA5MTcyMWQ2ZjU1MTMyMDU4MjEwMGQ2MzM5NTYxM2ZmZTM3OTk5OGM3NmU1OGRmNWYzNjc0Mzg2ZTI0ODM1Zjg5ZDAzYjllOTY2NzU5YjcyZGVkMTE0NzRlNzJmOWQ5ODI3MWQ4YTg2Y2ViYjk0YTcyM2Q2ODZkYjQyZThiNGE4NWE5NmFmZDEyYmE2MDRkNzIzMWMyNGIzZTE0MDRlMTgzOGJjM2I0YjIyYmY1Nzg4OGZkMmM0Mjg2OWQ2M2Y2MWMzZGMyMzk2MGM3NTBkNTg0MGZiMTZjNGFlN2U1ZjVhNzk5NTZhNTBkMTJkMjc4ZWUzZGM3ZGRlM2Q1ZjQyOTMzZTk3OWE4OWFlNWY5MmJiZTAzZmJlNjFhZGM0OGEyZmI2ZGEwNTA1N2NjMTVjYmM1MWRjYWM4YzY0MzcxOWEzN2FhMjJlODZiMTBiNjc4OGQ5MzI4NjRmMjk4NmJjMTFhZWZiZGRiNGZjM2I0YzQ2NjE4ODY2ZWQ3ZTE2M2MzMzgzYjA4YmY3MGJlNzAzMjlmMWUxOTI2MDRmOTFkMTNiY2ZjZDg1YjQzODg3ZDlmNTljZmQ%3D*&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;D_pzExplorerCaseTypes.pxResults(1)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTQzMDI2ZDgzN2ZlZDA5MTcyMWQ2ZjU1MTMyMDU4MjEwMGQ2MzM5NTYxM2ZmZTM3OTk5OGM3NmU1OGRmNWYzNjc5YTczOGViYTE0ZmE0ZGMyODdhMzY1ZmFiNWIzNTBmYTM5ZmQwYTc3ZmE4M2NlMmRkNzhiZDc5ODdmYTdkODNhMWUyNzQ3MjYxMzIyY2Y3NTM2N2U2NzU1ZjA4YTAyZTU1MmI3YjIxMGM0MWQ5YzgxNDc5ZWMyNGI2YTViYWIyMGU4OTYwZmFhYzYwOTFkMzYwZWUwYTYxNzI1NjRjY2RiMzk2YTgwZjE0MzFlZTM1NTA0YWZiNDFiODBjYmUxNDc0NTdjZjE1MjlhZWVlYzBhOGEzZWZjYjQ1NzE5M2E3ZA%3D%3D*&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzExplorerCaseTypes&quot;, &quot;pzFlushDataPage&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4NWY2MmIyZjI4NDFkYmE0M2M5NGEzZjVlMjI1NGZjZWI3YTllZjA0ZjhiOTU0MWY3NzExNDk3NDhmZjY5OWRiNGRhOTU2MTQyYWE2MWM3MzM0ZDM3YzdjZjE1NGY2OTA1YWI0Zjk5N2I2MDJmNTIyMmM0NzNkNjBkNzM2NGI5NmQ4MDRkNzRlNmIxYzM5NGIyMDZlNmQ3OTBjNDcwNzBmYWI1ZDQ1OWFlNjU0ZDRmN2M0OTZjYjkxMzM5Y2U0MzVkYjg1MTFlZjg5ZTAyYzRiNjFiYmI5ZDBhMGZhZGM3ZjgzNDBmNTg1ZThlMzk0OWFmNWU1NjdlZmRmN2JkNzk2ZGRmYWYzY2VhNGI3OGY5MGZlYTkxZDY3NDY3NDc0M2RlNTBmMDE3NzIyOWViMmI0MDQ3YjQxYTI4ZTdhNzliYjY4ZDU1YmMxMmUzYjkyYzM4M2M3ZjFhM2RjNWViNGJhMGNjNjg1M2I1NzIyMjJiMmE3ZGFmYzRiYTFmY2Q4M2U1MjRkNDU5MmU2Y2M3ZTYwOTZkOTMwNTM5YjVhNzcwMGNkNjg3NWRhZDg0NWUwNTlhZjc2NDJjMzE0ZjE3ODRhNGQ1ZjEzZmM2Yzg0ODFhMTY0MDE1NmMzZTZkMzgyMDY1MGFlZGIyNmEzYzI0YWFiMWFlMzhlMDVlMDgzNGJhMDc2MmY3ZjM0OGYwNGVkZTBmMGFiMzBjYjQyMGU0MDRkNzdmMTVmNmMwYzdjZWZkMjUzMjk0Mjk4NjRlYWExZWIyMWJkYTJlNTU5YzJmODE1YmZkZjkwNjA0MjI5YWI5NDI3YzVjNDljOTgxMzY0NWU3MzYyZDNlYjE0ZmFkM2E0OWRmMzdlODYxM2EyZDAwNTM5OTZhOGNiYjgwMTdlODA0ZmVlMTdkZjZjZTI3MTc3ZWY5ODk0ZWRkZWFiODI2MGQyNzczNmQxYWMzZWVmMDViNDljYjBiOGY4YTU1YTRjNThkMDBmY2Q4ZDMyMWQ0MzZlZmUxOTIxN2NjYjE3MDNlOTE5N2Q3OTEwYWU1M2FhM2U4NWE5ZGFlZTg2MTc2ZGM3NjFmNjk2MjZhZWVmNGU3MTBmYWM4MTA1NDVmZWZlYzVhODUwZTYxZDNjNTNjMWU1ODEyMjBjNWM0NDY0NTc2*&quot;,{&quot;DataPageName&quot;:&quot;D_pzExplorerCaseTypes&quot;,&quot;ParamName1&quot;:&quot;&quot;,&quot;ParamValue1&quot;:&quot;&quot;,&quot;ParamName2&quot;:&quot;&quot;,&quot;ParamValue2&quot;:&quot;&quot;,&quot;ParamName3&quot;:&quot;&quot;,&quot;ParamValue3&quot;:&quot;&quot;,&quot;ParamName4&quot;:&quot;&quot;,&quot;ParamValue4&quot;:&quot;&quot;,&quot;ParamName5&quot;:&quot;&quot;,&quot;ParamValue5&quot;:&quot;&quot;,&quot;FlushAllInstances&quot;:&quot;true&quot;},{}],&quot;D_pzExplorerCaseTypes.pxResults(1)&quot;]],[&quot;runScript&quot;, [&quot;pega.ui.composer.formfactor.reloadPreview()&quot;]]]</value>
      <webElementGuid>9ab22cf6-e153-47c4-bf69-d226cdeb3e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzDeleteCaseTypeWarnMessage_D_pzExplorerCaseTypes.pxResults(1)_6</value>
      <webElementGuid>f698e47f-8fe8-4bcd-91f0-0c71339e8e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>72143581-66cc-4985-b01a-84ea9ac181ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cb1a0f9-86e9-4004-b457-366bc3260be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>7d063da1-52b8-4d0b-98d8-884fef0917a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle auto-width-column clearfix&quot;]/div[@class=&quot;content-item content-layout item-1 remove-left-spacing remove-right-spacing float-right set-width-auto&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-bottom-spacing remove-right-spacing&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>4a45064f-fd46-418d-882d-cd92acc68dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzDeleteCaseTypeWarnMessage_D_pzExplorerCaseTypes.pxResults(1)_6']</value>
      <webElementGuid>5a6b79b0-eed9-4fe1-a216-d154aecc3255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div/div/div/div/div/div/div/div/span/button</value>
      <webElementGuid>cdece14c-9514-41b6-b9a1-e423c3e958dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pzDeleteCaseTypeWarnMessage'])[1]/following::button[1]</value>
      <webElementGuid>bc3dc7ab-aade-4095-b4b2-cd324a08ad02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Case Type'])[1]/following::button[2]</value>
      <webElementGuid>2fcd1d38-5931-4b0f-88d9-7f72b864c754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish all'])[1]/preceding::button[2]</value>
      <webElementGuid>d4086fcd-c148-481d-b296-06145c1b4996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard all'])[1]/preceding::button[3]</value>
      <webElementGuid>70e52c8d-9b61-48a6-be32-152b0973da21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/span/button</value>
      <webElementGuid>0e63d4a0-5c00-474b-a3dd-0ea254105580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzDeleteCaseTypeWarnMessage_D_pzExplorerCaseTypes.pxResults(1)_6' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>202ce1aa-5f15-4827-af3e-97ab565f8b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
