<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>55d20f40-62e4-461d-98f0-ada34e7dd911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pzModalNextButton_pyWorkPage_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzModalNextButton_pyWorkPage_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50ed43a7-fe3c-46ee-933e-3784a0dbc040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202003240614170687236</value>
      <webElementGuid>8b2d7a43-3c27-46ad-8da7-05b7d46f75c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzEnterCaseTypeInformation&quot;, &quot;pzValidateCaseTypeInfoWrapper&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzLyRGbG93TW9kYWxQcm9jZXNzfWQ0ZGUwZmY0ZTdhZjZlY2NkMjMwZTAxMmE4NjZjNTJkODlmZWRmMTY3MjU4ZWRkZDE2OWUyMDAyNmU1MmM0MWY2NTFhMzllMjNlODNhNDE3NDZlZDE3MmZkMjFhZDAwOWE2Y2M2YTFjYTE2MDYxOGI0MjA3YmEyODVkMTY2ZTQwYzFhMGJhNmNiNmFmY2JiNTAwY2YwZjJjMjRjZWE5NzAxM2ZiN2Y1NWRlYmVmMWQwNDc4YWI1YWQ4ZWYzNTA4ZDIxOGNhYjVlNDk2ZDdmNzA3ZGNjYzg2NWM1ZjdjMzVj*&quot;,{},{}],&quot;pyWorkPage&quot;]],[&quot;runScript&quot;, [&quot;pega.p.doClearActions(\&quot;#~NewCaseTypeStages.pyDoClearActions~#\&quot;)&quot;]],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;setUserStart&quot;,[&quot;FINISHASSIGNMENT&quot;]],[&quot;doFormSubmit&quot;,[&quot;pyActivity=FinishAssignment&quot;,&quot;:this&quot;,&quot;&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>d1c6cbcb-b9e6-438b-a69e-6f5843813951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzModalNextButton_pyWorkPage_2</value>
      <webElementGuid>5f789a8f-7754-4f01-8cd9-c226d65c5455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>c027cd1b-0f85-4fa5-ad82-8377d10a9f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e23d3c2-0b04-4b04-ad8a-5592c385ca29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next   </value>
      <webElementGuid>18c4a4de-9cd2-4dcd-807e-acab941cb221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalContent&quot;)/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  set-width-auto margin-0&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto margin-r-0&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-right-spacing flex flex-row margin-r-0&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-mimic_a_sentence  content-mimic_a_sentence clearfix&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>f38006ee-35a9-47d4-860c-994c2b51ea0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzModalNextButton_pyWorkPage_2']</value>
      <webElementGuid>954dc07b-0a41-42e6-8a0d-0b00b56441d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div[2]/div/div/span/button)[5]</value>
      <webElementGuid>bcf5cf99-455c-416c-a7cc-ccf74b5f5b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[1]</value>
      <webElementGuid>ca5b93fc-010e-4942-96d5-b1b3de4d0948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[2]</value>
      <webElementGuid>96b4816a-b62c-46ce-8e12-29d5474580d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsaved changes'])[1]/preceding::button[1]</value>
      <webElementGuid>1eaa1d64-a813-43b4-898e-d2328df8c24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are about to discard your unsaved changes.'])[1]/preceding::button[2]</value>
      <webElementGuid>e03a9cc7-11a5-46d3-a6b0-c59d393bcb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/span/button</value>
      <webElementGuid>eab2f005-8738-4531-b160-bcd96fa1ba83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzModalNextButton_pyWorkPage_2' and @type = 'button' and (text() = 'Next   ' or . = 'Next   ')]</value>
      <webElementGuid>51eab2cd-7337-4c23-9280-81078da994f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
