<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>7eb9d75a-1e4f-421b-9366-3a909c4d3513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzSaveAndRunCase_CaseTypeStages_31&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pzSaveAndRunCase_CaseTypeStages_31']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b92d120-8e28-4209-81d6-6ac31d715ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014092311173805466485</value>
      <webElementGuid>09c9d6c9-bf49-4cde-bebb-2a61564d357c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setValue&quot;, [[&quot;CaseTypeStages.pyWorkPageName&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;Saving&quot;]]],[&quot;runScript&quot;, [&quot;pega.cd.refreshCaseSettingContext(\&quot;#~CaseTypeStages.pyReference~#\&quot;)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzDisplayCaseTypeLifeCycle&quot;, &quot;pzSaveCaseTypeFromLP&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmY1MzJmMTg4Nzc3NjQ5Njg0MTJhZjMzYzFhZDc5NGU4ZDM3ZWNhNWI2ZWViMGUzZTJhN2ZhYzIzZmIxNGRiMDE5NGE3YjNkYjcyYTkwOGQyNWM5ZWJjNTUzYTAyMTIwZGFhNmZlOTYxMDAyMWNlMzgwZWE4ZmZkMWQzOTRhMWVmMWM0Y2I2ZWM3N2RhZDdiYmEyMTVjMWQwYzYyNGQ4Yzc0Mjk4ZTNlZDIxMDZkZGFmOGFkMmFjNjAxODhlN2Y3NzEyNmM2MWYwMWRlMThhMGM4YzhkMWMwZWU3MDZiMDA1*&quot;,{&quot;SaveCaseType&quot;:&quot;&quot;},{}],&quot;CaseTypeStages&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzCaseTypeLPHeader&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmVjMzA3N2MzY2ZkODk2YzVkY2UxZTZmMzVkZWEzOTBk*&quot;,{},{}],&quot;CaseTypeStages&quot;]],[&quot;runScript&quot;, [&quot;pega.cd.refreshCaseSettingContext(\&quot;#~CaseTypeStages.pyReference~#\&quot;,\&quot;false\&quot;)&quot;]],[&quot;setValue&quot;, [[&quot;CaseTypeStages.pyWorkPageName&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;Save&quot;]]],[&quot;runScript&quot;, [&quot;clearQueueConditionally(\&quot;#~CaseTypeStages.pyRuleDirty~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;pega.u.d.clearDirtyState()&quot;]],[&quot;runScript&quot;, [&quot;pega.u.d.clearReloadedStatus()&quot;]],[&quot;runScript&quot;, [&quot;pega.p.doClearActions(\&quot;#~CaseTypeStages.pyDoClearActions~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;pega.collaboration.actions.updateCollaboration(\&quot;#~CaseTypeStages.pzCollaborationHandle~#\&quot;,\&quot;save\&quot;)&quot;]]]</value>
      <webElementGuid>2409c48e-6082-4341-b938-5167d89e66c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzSaveAndRunCase_CaseTypeStages_31</value>
      <webElementGuid>bca7756e-95de-4438-ad4d-6ff050dba953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>0992ea13-c818-4498-8210-12fc8cde9594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f95a5b8c-39e0-4b6c-97b0-d27dee64108d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to Save</value>
      <webElementGuid>26ffbc39-0264-4e9b-af71-0ac66c7cf5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>5d12e330-1872-4b7e-9b64-c5ead4d141de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/header[@class=&quot;workarea-view-header workarea-view-header-fixed&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[1]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  layout-box-shadow&quot;]/div[@class=&quot;content-item content-layout item-3 align-end set-width-auto flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-bottom-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  nowrap right-aligned ruleform-header-actions&quot;]/div[@class=&quot;content-item content-layout item-4 remove-top-spacing remove-bottom-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-1 remove-all-spacing flex flex-row hotkey-ruleform-save dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>e1e2b591-9306-44b5-b718-e748dbf1fe15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzSaveAndRunCase_CaseTypeStages_31']</value>
      <webElementGuid>3f8f32d6-df77-4020-936f-d154a635a928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div[4]/div/div/span/button</value>
      <webElementGuid>5bae917c-54f7-42d6-9931-55b736868971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saving...'])[1]/following::button[1]</value>
      <webElementGuid>a694f952-bc37-4a42-a126-53dc3b7180e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and run'])[2]/following::button[2]</value>
      <webElementGuid>b093d7a3-af97-4e88-93b0-7c16aba3df85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saving...'])[2]/preceding::button[1]</value>
      <webElementGuid>f983f520-217c-4da8-a61b-0bf120fd5b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflow'])[1]/preceding::button[2]</value>
      <webElementGuid>e463914d-9e87-4bf1-a4bf-3644adbe0cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/button</value>
      <webElementGuid>e96e14eb-fe8e-4f72-92f2-4c5ba6c22158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzSaveAndRunCase_CaseTypeStages_31' and @type = 'button' and @title = 'Click to Save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>cffe57ba-abf4-4f40-aa92-7a01ceec1fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
