<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Preview</name>
   <tag></tag>
   <elementGuidId>b3d7c632-f461-44ef-86f4-79da90a01a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzComposerBarRight_pyPortalHarness_18&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pzComposerBarRight_pyPortalHarness_18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47b173c7-4938-4cf8-a147-a4e9d12b2396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>back-to-preview-btn</value>
      <webElementGuid>8a9d2994-fac6-4d64-9925-5ad37a943441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runScript&quot;, [&quot;formFactorIframe.backToPreview(\&quot;#~D_pzAppViewSettings.pySelectedChannelClass~#\&quot;)&quot;]]]</value>
      <webElementGuid>97511153-3262-46ce-a158-3c7a89104681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzComposerBarRight_pyPortalHarness_18</value>
      <webElementGuid>71427d7c-b858-4b40-9bac-9037833c163d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Icon_light pzhc pzbutton</value>
      <webElementGuid>5ee9f172-0ff2-41e8-b151-1fd425c822a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eae69e46-157d-4056-b336-02486ea99987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>d5c9ca63-cf1d-4015-a50c-d05a09d3da09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none  float-right set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-header_menu_secondary  content-header_menu_secondary set-width-auto&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-all-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-header_menu_secondary  content-header_menu_secondary auto-width-column&quot;]/div[@class=&quot;content-item content-layout item-2 remove-all-spacing set-width-auto flex flex-row&quot;]/div[@class=&quot;flex content layout-content-header_menu_primary content-header_menu_primary set-width-auto back-to-preview&quot;]/div[@class=&quot;content-item content-field item-1 flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Icon_light pzhc pzbutton&quot;]</value>
      <webElementGuid>5ce0edcb-a9ec-4885-8d28-447aa00b9813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzComposerBarRight_pyPortalHarness_18']</value>
      <webElementGuid>9ffac4ac-88d5-4da7-8da5-12745350e2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div[2]/div/div/span/button)[4]</value>
      <webElementGuid>13c6eefa-fb0f-4c14-98de-c51b43fa6fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit preview'])[1]/following::button[1]</value>
      <webElementGuid>1b98076e-e125-4f2a-ade9-c4398da1921f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design'])[1]/following::button[2]</value>
      <webElementGuid>08dc2067-deaa-4b4a-8980-12e71c7e68cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEVELOPMENT'])[1]/preceding::button[7]</value>
      <webElementGuid>93601404-b86e-448d-80c0-006feea961d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Studio'])[2]/preceding::button[7]</value>
      <webElementGuid>995d54da-b858-4d8b-90c0-c934676a3178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview']/parent::*</value>
      <webElementGuid>0ddb63c8-1fc0-4ef5-be96-0176b035dfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/span/button</value>
      <webElementGuid>4e7d2692-6724-4721-80f3-861b95f585af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzComposerBarRight_pyPortalHarness_18' and @type = 'button' and (text() = 'Preview' or . = 'Preview')]</value>
      <webElementGuid>8aae662d-df6d-464f-a5c8-bb0315f424e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
