<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1</name>
   <tag></tag>
   <elementGuidId>5e2bc2b7-d339-4fa1-8203-938ef8e323f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzConfirmDeleteDataClass_D_pzDisplayAppDataTypeList_pa3697443897072pz.pxResults(1)_12&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Delete Data Class'])[1]/following::button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf1a239a-2a05-4e46-89a8-307fe9b67bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201503171638260869104993</value>
      <webElementGuid>0d413867-f16e-4759-bc08-4ab6cecb97e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;D_pzDisplayAppDataTypeList_pa3697443897072pz.pxResults(1)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTQzMDI2ZDgzN2ZlZDA5MTcyMWQ2ZjU1MTMyMDU4MjEwMGQ2MzM5NTYxM2ZmZTM3OTk5OGM3NmU1OGRmNWYzNjc5YTczOGViYTE0ZmE0ZGMyODdhMzY1ZmFiNWIzNTBmYTIyNjY3NGUyYThlOWQyZGQxOTIzNWFhOWE5OTk2OGM2ZTVlZjE3MDQyZDY3NDgyMWNiM2JmNzY3NjRjNGRhMWViZjRmZjI3NTJjMzM3MjA0NmNmNDdhYjFiYTkyNzg0MmM1NWY1MGU1NTJiMGJkYjA1ZGJmMDI0Mzc2YmFiNjI0YzI2MDI5ZTZiMjkyMDQ0MzQzNzZjNjMyZTNmZDZkYTU%3D*&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzLPDisplayAppDataTypes&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmVjMzA3N2MzY2ZkODk2YzVkY2UxZTZmMzVkZWEzOTBk*&quot;,{},{}],&quot;D_pzDisplayAppDataTypeList_pa3697443897072pz.pxResults(1)&quot;]],[&quot;closeContainer&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>82cec40d-0b73-4a21-9b69-c43fc13209ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzConfirmDeleteDataClass_D_pzDisplayAppDataTypeList_pa3697443897072pz.pxResults(1)_12</value>
      <webElementGuid>19b1c3f0-98b4-4f1c-a76b-8e4d371fbb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>7511837d-3a2c-4aef-a62c-ad62254b5f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63fb6a92-135e-4876-968a-e78669c7e247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>da67eef2-dce1-45cb-b1ab-213eb3d5497b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-layout item-2 flex flex-row&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-modal_button_array&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle auto-width-column&quot;]/div[@class=&quot;content-item content-layout item-2 remove-left-spacing remove-right-spacing float-right set-width-auto&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-bottom-spacing remove-right-spacing&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>dd5fe0d1-ec7a-4611-a27c-0159510e98c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzConfirmDeleteDataClass_D_pzDisplayAppDataTypeList_pa3697443897072pz.pxResults(1)_12']</value>
      <webElementGuid>a73c68f5-e76c-4528-81e3-c1ee70fb90a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div[2]/div/div/div/div[2]/div/div/div/div/div/div/div/span/button</value>
      <webElementGuid>e35cf829-7d5f-4c99-bddd-54959ed0da60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>055f90f1-e164-4d81-8483-059f67d760cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Delete Data Class'])[1]/following::button[2]</value>
      <webElementGuid>4341442f-1ccf-40ea-8e41-beb1e8ac1388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish all'])[1]/preceding::button[2]</value>
      <webElementGuid>4f806ee2-d13f-4afa-8666-cad9a0edf544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard all'])[1]/preceding::button[3]</value>
      <webElementGuid>b8ec2fbc-0f7c-4b77-94e8-1c5a7cd78a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/span/button</value>
      <webElementGuid>f01dc0c3-7077-40ee-bbf7-020a4af4d210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzConfirmDeleteDataClass_D_pzDisplayAppDataTypeList_pa3697443897072pz.pxResults(1)_12' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>fc83056f-1aba-4b77-bf10-917fb378c913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
