<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create Case Type_PNewCaseTypeStagesppyLabel</name>
   <tag></tag>
   <elementGuidId>452d06fa-7b5f-4ba9-843a-163f5648792e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eebf78aa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eebf78aa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db761e33-fbb4-4a4a-b772-8c1904dfb8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;setValue&quot;, [[&quot;NewCaseTypeStages.pyDescription&quot;, &quot;&quot;, &quot;NewCaseTypeStages.pyLabel&quot;, &quot;&quot;,&quot;#~NewCaseTypeStages.pyLabel~#&quot;]],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PNewCaseTypeStages$ppyDescription&quot;,&quot;=&quot;,&quot;&quot;,&quot;true&quot;]]]]]</value>
      <webElementGuid>af964f8b-761d-4fda-b929-bafe292f2bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keydown</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;],,&quot;enter&quot;],[&quot;setValue&quot;, [[&quot;NewCaseTypeStages.pyDescription&quot;, &quot;&quot;, &quot;NewCaseTypeStages.pyLabel&quot;, &quot;&quot;,&quot;#~NewCaseTypeStages.pyLabel~#&quot;]],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PNewCaseTypeStages$ppyDescription&quot;,&quot;=&quot;,&quot;&quot;,&quot;true&quot;]]],&quot;enter&quot;],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;pzValidateCaseTypeInfoWrapper&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzLyRGbG93TW9kYWxQcm9jZXNzfWQ0ZGUwZmY0ZTdhZjZlY2NkMjMwZTAxMmE4NjZjNTJkODlmZWRmMTY3MjU4ZWRkZDE2OWUyMDAyNmU1MmM0MWY2NTFhMzllMjNlODNhNDE3NDZlZDE3MmZkMjFhZDAwOWY3Y2IwMWZlMjQzYzkzZGM0NTM0Nzc0ZTZmNjkzODMxZjhlYmI3MjUwY2I3YjRjNGI1NmYzNzY2NjI3MDZjMDIwM2RkZjQwOTBkZmFhZWY4MDdlZDhhODI3ZjU0ODhjYjM3N2I4ZjdhOTA1MWFlYmUxOTEyYzhlZmZmMmFlZjAwODVhYzkzZjQyZGViMmJjMTU4OTRmOWQxNzQxNzBhMWM2ZGM0ZWMxZjc5MDVhYWJjMGEyNTc1MGU4ZmY3Njg4Yw%3D%3D*&quot;,{},{}],&quot;NewCaseTypeStages&quot;],,&quot;enter&quot;],[&quot;runScript&quot;, [&quot;pega.p.doClearActions (\&quot;#~NewCaseTypeStages.pyDoClearActions~#\&quot;)&quot;],,&quot;enter&quot;],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;setUserStart&quot;,[&quot;FINISHASSIGNMENT&quot;]],[&quot;doFormSubmit&quot;,[&quot;pyActivity=FinishAssignment&quot;,&quot;:this&quot;,&quot;&quot;,&quot;:event&quot;],,&quot;enter&quot;],[&quot;postValue&quot;,[&quot;:event&quot;],,&quot;enter&quot;],[&quot;setValue&quot;, [[&quot;NewCaseTypeStages.pyDescription&quot;, &quot;&quot;, &quot;NewCaseTypeStages.pyLabel&quot;, &quot;&quot;,&quot;#~NewCaseTypeStages.pyLabel~#&quot;]],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PNewCaseTypeStages$ppyDescription&quot;,&quot;=&quot;,&quot;&quot;,&quot;true&quot;]]],&quot;enter&quot;],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;pzEnterCaseTypeInformation&quot;, &quot;pzCreateCaseTypeWrapper&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzLyRGbG93TW9kYWxQcm9jZXNzfWQ0ZGUwZmY0ZTdhZjZlY2NkMjMwZTAxMmE4NjZjNTJkODlmZWRmMTY3MjU4ZWRkZDE2OWUyMDAyNmU1MmM0MWY2NTFhMzllMjNlODNhNDE3NDZlZDE3MmZkMjFhZDAwOWY3Y2IwMWZlMjQzYzkzZGM0NTM0Nzc0ZTZmNjkzODMxZjhlYmI3MjUwY2I3YjRjNGI1NmYzNzY2NjI3MDZjMDIwM2RkZjQwOTBkZmFhZWY4MDdlZDhhODI3ZjU0ODhjYmIzNzkyYTk5ZDIzNGI2YTc3ZTdkNjA3ODU3ZjA0ZDVlZDE4YTE5YTQ5YzEyYjUxMDRjMTBkNzQ4MTA3MGU5ZGZjZDk5MzhlNmU4MTU4MjY0ZjkyNDc2ZTA4ZmNmMGViZDllZDc4YzVkYmRmM2Y5ZGUyNWRlZDdjYTU2YTdlMmY3ZjhmYTcxMTc1ZTBlMGJlNzZkNGM3NmJhNTU0MjEyYWFiZjZmNDIyNjUzY2QyYTQxZDc0ZGM1MmFkODU0YzJkMw%3D%3D*&quot;,{&quot;skipStages&quot;:&quot;true&quot;},{}],&quot;NewCaseTypeStages&quot;],,&quot;enter&quot;],[&quot;runScript&quot;, [&quot;pega.p.doClearActions (\&quot;#~NewCaseTypeStages.pyDoClearActions~#\&quot;)&quot;],,&quot;enter&quot;],[&quot;closeContainer&quot;,[&quot;:event&quot;],,&quot;enter&quot;],[&quot;runScript&quot;, [&quot;pega.desktop.closeAllDocuments(event)&quot;],,&quot;enter&quot;],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;showHarnessWrapper&quot;,[&quot;newDocument&quot;,&quot;Rule-Obj-Class&quot;,&quot;pzCaseTypeLP&quot;,&quot;pzPrepareCaseTypeLP&quot;,{&quot;lpParamImmediateParent&quot;:&quot;&quot;,&quot;lpParamTopMostParent&quot;:&quot;&quot;,&quot;lpParampyCircumstanceVal&quot;:&quot;&quot;,&quot;preActivityDynamicParams&quot;:{&quot;lpParampyClassName&quot;:&quot;#~NewCaseTypeStages.pyClassName~#&quot;,&quot;lpTitle&quot;:&quot;#~NewCaseTypeStages.pyLabel~#&quot;}},&quot;NewCaseTypeStages&quot;,&quot;EditModeExpressTab&quot;,&quot;&quot;,&quot;No&quot;,{&quot;pyDataTransform&quot;:&quot;pzSetExpressSkinForEditMode&quot;,&quot;pyDataTransformParams&quot;:{}},&quot;:event&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;false&quot;],,&quot;enter&quot;]]</value>
      <webElementGuid>4ee45069-ac59-4dc5-8de3-fe28cc388d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20150317112515058014768</value>
      <webElementGuid>9444887d-07d8-4854-b587-ded46442d449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>b6faddc7-baf4-46b9-8e5c-5586b9e0b305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37425985-71bb-403f-9b52-2145ed6ceb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eebf78aa</value>
      <webElementGuid>0271d9e7-a12b-4447-af46-5b4bf55dfba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>42371c3b-0abe-4cfa-8dea-e66eb302a182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PNewCaseTypeStages$ppyLabel</value>
      <webElementGuid>363d332a-e31f-4e6f-bfb3-c8c46b719ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Case Type name</value>
      <webElementGuid>07a8e7e8-a945-4c3d-b2e8-c2b2756d30f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>44baf511-4cac-488e-b32a-3fd5b4b4fc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PNewCaseTypeStages$ppyLabelError </value>
      <webElementGuid>a37fe55c-ec28-4439-812c-159642f9fa62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ad7eed1-86f5-438f-be7d-b48612d62c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>330979b6-aa9b-45dc-84d0-d6ea0c5b4607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eebf78aa&quot;)</value>
      <webElementGuid>ab0c9374-6409-4071-8da2-464b771dca9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eebf78aa']</value>
      <webElementGuid>29a204a9-b829-4b8c-814c-56710cc41e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>7167a01c-3608-4f74-a719-f30c86792d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>426734c7-3148-48ad-ba0a-92a614c3b910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'eebf78aa' and @name = '$PNewCaseTypeStages$ppyLabel' and @placeholder = 'Case Type name']</value>
      <webElementGuid>69b1f0e3-1d00-4e58-ae41-aca9ebc172a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
