<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required_PCaseTypeStagesppyStagesl2pp_895c2f</name>
   <tag></tag>
   <elementGuidId>bcf57a5e-83ae-4d2a-b47d-cc2c3eb9819a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d3d7584</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d3d7584']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>581167a5-08ad-4ed6-b69f-9ca9b54c413b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20141028153356037623207</value>
      <webElementGuid>29ca2245-8c80-440d-890a-a5d525413d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>32e48050-9aec-49b5-af33-d37ba32762b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d3d7584</value>
      <webElementGuid>9cdc3ee7-3a98-401f-844b-3530add63787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>67614047-1b92-4f44-b38a-39e6dfe5271e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca64564d-a255-4078-8cdd-fdadd9968236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PCaseTypeStages$ppyStages$l2$ppyStageName</value>
      <webElementGuid>9cf1e8ce-733d-4dbc-be0b-0ffedf9691f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PCaseTypeStages$ppyStages$l2$ppyStageNameError</value>
      <webElementGuid>ffc70338-012b-49f8-b7eb-c5cd57d1b14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>553647d0-65be-4c96-a08c-7418713ff932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzStageMenu&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmVjMzA3N2MzY2ZkODk2YzVkY2UxZTZmMzVkZWEzOTBk*&quot;,{},{}],&quot;CaseTypeStages.pyStages(2)&quot;]],[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;editedName=#~CaseTypeStages.pyStages(2).pyStageName~#&quot;, &quot;CaseTypeStages.pyStages(2)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTQzMDI2ZDgzN2ZlZDA5MTcyMWQ2ZjU1MTMyMDU4MjEwMGQ2MzM5NTYxM2ZmZTM3OTk5OGM3NmU1OGRmNWYzNjc2NTI2YjNiZTQ2ZTczOWQ0MGJkNGJlZmQzMDdjODM1M2VhMzU3NGZmMTBlMWYzYWMyMGI5N2MyZTU1MzM0YjNhOTZkNjcyZDU5NzE1MGZiY2E3ZTkzZGQxNDkxOTMyOGEwZDc5M2UxMDRhNTFiYzIwYjRmM2NmZDY5NmRlN2IyMzJjMWQ0NTVkMjYzMTM3MzkxOTg0YmExNGRlNTRiYWNj*&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzStagesWrapper&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmVjMzA3N2MzY2ZkODk2YzVkY2UxZTZmMzVkZWEzOTBk*&quot;,{},{}],&quot;CaseTypeStages.pyStages(2)&quot;]]]</value>
      <webElementGuid>0182c126-9fd1-4947-9988-27ba7dc4dec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keydown</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;pzDisplayStageName&quot;, &quot;pzEnterKeyOnStageWrapper&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMjQzMDE1ZjMyNzFlZGM5NDI2NDFiMmM0NzlkMzExMTFjM2I1YjIyOGI0ZGExNmQyYTkxOTI1MGU5NTRhYTI2MTUxZDFiZDcxMDliNzk3ZTQ0ZWUxNjQxOTM3NzljODJjMDFkMGU5Mzk2ZjIwZjZmMzViMTlkNzcxYjQ0YzMzZjc1YmVmZTc4NTkzMGFmZWY0YjZjODZhMWQ0Mzg2ZjJjODE%3D*&quot;,{},{}],&quot;CaseTypeStages.pyStages(2)&quot;],,&quot;enter&quot;]]</value>
      <webElementGuid>cd03a8e6-a58a-4ad3-9494-e4231888e656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dab6a487-eddc-412a-982c-38b940223c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d3d7584&quot;)</value>
      <webElementGuid>72a7e141-3a11-44ad-81f4-4204a36438bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d3d7584']</value>
      <webElementGuid>20e13b8d-7c17-4b30-a31b-4c77416f4ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='CT']/div/div/div/div/div/div/span/input)[2]</value>
      <webElementGuid>8ca409d5-8c07-4fbc-ba79-23c321dbf60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/h3/div/div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>42510178-65f8-455f-b4cc-ddf293b6a814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd3d7584' and @type = 'text' and @name = '$PCaseTypeStages$ppyStages$l2$ppyStageName']</value>
      <webElementGuid>b7a0f04f-91ec-4925-87a4-7be562cabfb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
