<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data Object name_PpyWorkPageppyDataTy_ee8150</name>
   <tag></tag>
   <elementGuidId>f03f5322-fe00-40f8-b1ce-b0a9d4d6e81e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c9354739</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c9354739']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d2974d5-a7df-497a-ac36-30476d78ac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>a765e355-48b0-432f-8059-24cec337e7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014112001383408251897</value>
      <webElementGuid>fc9b1fce-4017-4f4a-bc23-1b8620736285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>545cfd86-1edf-43fe-9ae3-0c344e74a5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3bb67e5-ec1a-4455-b3d2-45eb6cbe42ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c9354739</value>
      <webElementGuid>bd3b6a26-98a8-4dc6-b256-f508f3351b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>b3ba5066-195e-424f-b154-ca440e623dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyDataTypeDetails$ppyLabel</value>
      <webElementGuid>ec60a4cf-2d98-45b2-8504-cca7038028ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>45fc404b-2763-4758-ba8b-15d6e5fa5e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyDataTypeDetails$ppyLabelError </value>
      <webElementGuid>c85e398a-4d9e-45d8-92bd-8f30218eca39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d31b042-522f-4e44-bb06-016f07c269aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d03398d-87c4-47c8-ab27-508523f58e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c9354739&quot;)</value>
      <webElementGuid>9c8e0d4e-f50c-477e-8eba-79bb028ae836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c9354739']</value>
      <webElementGuid>6ced6ada-422a-4824-8092-8d5504222445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div[2]/div/span/input</value>
      <webElementGuid>d273e25f-26d7-4961-af1e-8da337e38180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div[2]/div/span/input</value>
      <webElementGuid>7f335d5d-7562-40ee-a3a3-b8e479ac4cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'c9354739' and @name = '$PpyWorkPage$ppyDataTypeDetails$ppyLabel']</value>
      <webElementGuid>83bcef2a-c0fa-433a-84d8-73529df812e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
