<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required_PCaseTypeStagesppyStagesl1pp_c38d07</name>
   <tag></tag>
   <elementGuidId>e3ec0517-609e-40e2-b1f3-10791134e331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1fa53e5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1fa53e5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7954e20-4cb7-4257-bf04-1c2580fdc1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20151104025120034821786</value>
      <webElementGuid>924ff0ab-0335-451e-9e06-2bed58d066cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>3627267e-2be0-43ef-977b-6eb989d61369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1fa53e5</value>
      <webElementGuid>f8c64fcc-624e-4a40-a52f-d2d40e10e584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>80c83ef4-29ac-4fba-af14-3a65e76578c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3866d71-788d-4015-a1bb-388ae29819d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Collect Information</value>
      <webElementGuid>cd49848c-da0c-496b-b5c4-23f99d9a156f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PCaseTypeStages$ppyStages$l1$ppyProcesses$l1$ppyShapeNodes$l2$ppyShapeName</value>
      <webElementGuid>d3f55d91-111b-48de-afb3-0e162794a264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PCaseTypeStages$ppyStages$l1$ppyProcesses$l1$ppyShapeNodes$l2$ppyShapeNameError</value>
      <webElementGuid>e1ce59d9-d966-4d1d-a5af-fee9b8820d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>cf12b90b-515e-4fb0-aed9-4e5feed02aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;pzDisplayCDCompatibleShapes&quot;, &quot;pxRename&quot;, &quot;EditedLabel=#~CaseTypeStages.pyStages(1).pyProcesses(1).pyShapeNodes(2).pyShapeName~#&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMjQzMDE1ZjMyNzFlZGM5NDI2NDFiMmM0NzlkMzExMTFjZmNiZmI3ODMyYzkzYzMwMzQyMzAzZDA1MDdjNWQxOGVmMTMzN2FlZDNkZjI3N2IzN2I5ZWFiNmIyODg5MzA2MGRjYThlZmYxMjQzYWY1MjA1MTBkZTBmN2RmYzZiODI4MDA4ZTFlYmVjMTQwNjJlNDJlOTRjOWRhOWRkNjI2MDc%3D*&quot;,{},{}],&quot;CaseTypeStages.pyStages(1).pyProcesses(1).pyShapeNodes(2)&quot;]]]</value>
      <webElementGuid>ca165ae3-d469-430b-8f8d-1efe65a66fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keydown</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;REFRESHROWS&quot;,null,{&quot;offset&quot;: &quot;0&quot;,&quot;bDisableSubmit&quot;: &quot;false&quot;}],,&quot;enter&quot;],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;CaseTypeStages.pyStages(1).pyProcesses(1).pyShapeNodes(2)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTQzMDI2ZDgzN2ZlZDA5MTcyMWQ2ZjU1MTMyMDU4MjEwMGQ2MzM5NTYxM2ZmZTM3OTk5OGM3NmU1OGRmNWYzNjdkN2JhNTMyNmYzZjMzYTY4MTE0NmUzYTAzNzY5Zjc4ZjgzNTI0YTA2ZDJjZTE2YjM4ZTc3OTM0NmYwNDg4MWI2MTZlYjQyYjRlODhjMzZjNzRhODAxMTFkNzIzZDQzOGEzMmIwZTMzMzFiOWRiOTU3ZWY0YTc5MDBhNjE1YWMyZTM0MDJjYjRjNGI4OWEyZGZlNWU5MDY0Y2RkZmRmMTEwNWRiYmVlMjdiNDU4M2JmNTQ3M2VkZjJkY2FjMTIwZWM%3D*&quot;],,&quot;enter&quot;],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pzDisplayAddStep&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17RENTUEFfcHhFeHByZXNzfTY1MjliYzI4MDU0NzZiMDU5OGY4MThhMmQ3Mzc4MTJlZTk2ZGZlYTg2YWY1NGIzYTJmNzczNDlkMjI4Y2Y4YWM5OGZiZjRiOTM1M2RmZDUyMGZkZWJhZmNkYTMyNTBmMmVjMzA3N2MzY2ZkODk2YzVkY2UxZTZmMzVkZWEzOTBk*&quot;,{},{}],&quot;CaseTypeStages.pyStages(1).pyProcesses(1).pyShapeNodes(2)&quot;],,&quot;enter&quot;]]</value>
      <webElementGuid>d2ec436c-1d47-4bb9-af51-4f29da63a94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69e8877e-c505-4cab-9c59-60a80e422d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1fa53e5&quot;)</value>
      <webElementGuid>79697dfb-f47c-49b2-9de6-6178b51c8251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1fa53e5']</value>
      <webElementGuid>14922c19-243b-48fb-8c90-5b7dc732527d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='CT']/div/div/div/div[2]/span/input)[3]</value>
      <webElementGuid>9cef58f4-68d5-4aef-9288-9e29c89f39ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/div/div/div/div[2]/span/input</value>
      <webElementGuid>45541be1-c879-4de8-b2bd-086205b18c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1fa53e5' and @type = 'text' and @placeholder = 'Collect Information' and @name = '$PCaseTypeStages$ppyStages$l1$ppyProcesses$l1$ppyShapeNodes$l2$ppyShapeName']</value>
      <webElementGuid>8a54eabe-5d50-4d09-beca-3f644d11bf5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
