<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Trials</name>
   <tag></tag>
   <elementGuidId>3cec0d68-f365-44b6-9127-1aa542060fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'My Trials')])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;NavigationLink_D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1)_12&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>defb61ec-f852-4414-a702-6b91aa4023f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;SetNavigationLinkProperties&quot;, &quot;URL=&amp;ClassName=&amp;PreProcess=&amp;TempDPName=&amp;TempPropName=&quot;, &quot;D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1)&quot;,&quot;:event&quot;]],[&quot;runScript&quot;, [&quot;collapseNav(event,\&quot;#~D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1).Category~#\&quot;)&quot;]],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;showHarnessWrapper&quot;,[&quot;newDocument&quot;,&quot;#~D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1).ClassName~#&quot;,&quot;#~D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1).URL~#&quot;,&quot;ApplyNavigationLinkPreProcess&quot;,{&quot;&quot;:&quot;&quot;},&quot;D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1)&quot;,&quot;#~D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1).TabName~#&quot;,&quot;&quot;,&quot;No&quot;,{&quot;pyDataTransform&quot;:&quot;SetOperator&quot;,&quot;pyDataTransformParams&quot;:{}},&quot;:event&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;false&quot;]],[&quot;runScript&quot;, [&quot;runNavigationLinkScript(\&quot;#~D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1).ScriptToRun~#\&quot;)&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PD_ListMyPegaLinksByLevel_pa1234149715339622pz$ppxResults$l1$pScriptToRun&quot;,&quot;!=&quot;,&quot;&quot;,&quot;false&quot;]]]]]</value>
      <webElementGuid>2ccc1a87-3a28-46f0-b877-d1071bc49c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5f1febbf-a1c0-45b0-b17a-f2a945c77d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href_original</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5269c976-60cf-4813-84e1-cd6dd3b3f285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>9998a6e9-9fed-419c-b1e7-3320147ada36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NavigationLink_D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1)_12</value>
      <webElementGuid>d934ccc3-0bd6-45af-aefd-523f64fd39a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Mega_Nav_item</value>
      <webElementGuid>c68b8b66-c596-4594-a9b8-e11698d1034b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Trials</value>
      <webElementGuid>ac292929-e26f-4ad4-9594-761c40c8fc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-bottom-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default portal-subheader margin-b-0&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  flex layout-max1400&quot;]/div[@class=&quot;content-item content-layout item-2 remove-top-spacing remove-bottom-spacing flex flex-row&quot;]/div[@class=&quot;rdlWrapperDiv&quot;]/div[@class=&quot;content    flex  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-sub_section item-3 remove-top-spacing remove-bottom-spacing flex flex-row mypega-main-nav desktop-nav&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-layout item-2 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline  mega-nav-overlay-inner&quot;]/div[@class=&quot;content-item content-layout item-1 remove-top-spacing remove-bottom-spacing remove-left-spacing flex flex-row&quot;]/div[@class=&quot;rdlWrapperDiv&quot;]/div[@class=&quot;content    flex  layout-content-inline content-inline mega-nav-child&quot;]/div[@class=&quot;content-item content-sub_section item-1 flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-layout item-2 flex flex-row&quot;]/div[@class=&quot;rdlWrapperDiv&quot;]/div[@class=&quot;content    flex  layout-content-stacked content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-1 flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_labels_left  content-inline_labels_left  content-items-maxwidth navigation-links&quot;]/div[@class=&quot;content-item content-layout item-2 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-layout item-1 remove-left-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  margin-b-0_5x&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing flex flex-row dataValueWrite&quot;]/span[1]/a[@class=&quot;Mega_Nav_item&quot;]</value>
      <webElementGuid>8b73296b-bbc9-4742-b576-9fb257f7627c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='NavigationLink_D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1)_12']</value>
      <webElementGuid>9e41c574-acff-493d-8549-d52153f26bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div[2]/div/div/div/div/div/div/span/a)[8]</value>
      <webElementGuid>f7c43313-a8ba-4ca3-a1ec-b7c1f5d32b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Trials')]</value>
      <webElementGuid>30819214-bccf-44c4-b905-694aee37c708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Your Pega Products'])[1]/following::a[1]</value>
      <webElementGuid>855ea29f-8f68-446b-b8ee-ad9f7825647f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software'])[2]/following::a[1]</value>
      <webElementGuid>1f912021-0efc-45ac-af4e-b483120b758d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Growth'])[2]/preceding::a[2]</value>
      <webElementGuid>cebc07ea-e3df-4d16-87d9-cf254cd50b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Succeed with Pega'])[1]/preceding::a[2]</value>
      <webElementGuid>a93a5f58-941e-4df3-acd2-496f3253f47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Trials']/parent::*</value>
      <webElementGuid>02a52f87-9eda-4e58-9936-ac11262a1d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[66]</value>
      <webElementGuid>72ef846e-e7a1-4ca0-8cc8-8e5c123d2cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span[2]/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div/span/a</value>
      <webElementGuid>c50e0d18-de46-441d-9026-53958a1af82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'NavigationLink_D_ListMyPegaLinksByLevel_pa1234149715339622pz.pxResults(1)_12' and (text() = 'My Trials' or . = 'My Trials')]</value>
      <webElementGuid>0a5bd72e-bc8b-4a57-b642-ae12645c3877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
