<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Software</name>
   <tag></tag>
   <elementGuidId>1c65ebac-efc3-42ed-9109-4fbad307356c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='NavigationLink_D_ListMyPegaLinksByLevel_pa1234149368512691pz.pxResults(3)_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;NavigationLink_D_ListMyPegaLinksByLevel_pa1234149368512691pz.pxResults(3)_8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7cbf0513-72f7-4324-9101-5c5104c40928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e4b30d3a-55ae-4826-8f89-6e811d13ed5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href_original</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ec788468-c3cf-484a-be5b-ea7a53619fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>5bd338df-1148-4906-99a7-7c5483c86755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NavigationLink_D_ListMyPegaLinksByLevel_pa1234149368512691pz.pxResults(3)_8</value>
      <webElementGuid>3445fea1-d264-46ad-93eb-1b28e06bf606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Mega_Nav</value>
      <webElementGuid>6a378957-624f-4283-acd7-6b034a9f6ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>7e9eae97-7298-4cb8-a653-9542258ea5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>83926e30-87a5-42e8-9630-df0ee5c8c8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>6d38c312-4572-4bf5-9bec-db10844917aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d86bf13-d2a8-4839-8691-0d918fb23eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9213e9bb-1e32-408a-927f-35783e838aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Software</value>
      <webElementGuid>d4509030-0090-495f-9c1e-8e0206728c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-bottom-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default portal-subheader margin-b-0&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  flex layout-max1400&quot;]/div[@class=&quot;content-item content-layout item-2 remove-top-spacing remove-bottom-spacing flex flex-row&quot;]/div[@class=&quot;rdlWrapperDiv&quot;]/div[@class=&quot;content    flex  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-sub_section item-3 remove-top-spacing remove-bottom-spacing flex flex-row mypega-main-nav desktop-nav&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_labels_left  content-inline_labels_left  content-items-maxwidth navigation-links&quot;]/div[@class=&quot;content-item content-layout item-2 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-layout item-1 remove-left-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-1 flex flex-row mega-nav-link dataValueWrite&quot;]/span[1]/a[@class=&quot;Mega_Nav&quot;]</value>
      <webElementGuid>01d6b6d9-eb32-47be-a04c-b2b60376909c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='NavigationLink_D_ListMyPegaLinksByLevel_pa1234149368512691pz.pxResults(3)_8']</value>
      <webElementGuid>0ee710f5-0218-46fe-8ceb-064b92d1332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div[2]/div/div/div/div/span/a)[22]</value>
      <webElementGuid>fd41b769-48ff-490a-b7cd-441ff9affc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Software')]</value>
      <webElementGuid>78a231c6-f70c-4351-8f38-b61ed0566590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work and Communicate'])[1]/following::a[2]</value>
      <webElementGuid>e579e769-9f60-45b1-88fd-fd7d77137a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaboration'])[2]/following::a[2]</value>
      <webElementGuid>86d57c0e-c58a-45db-9759-9e0d3532c6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software'])[2]/preceding::a[1]</value>
      <webElementGuid>ff7d0b16-0ada-4a24-b664-100726f25164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Your Pega Products'])[1]/preceding::a[1]</value>
      <webElementGuid>fe347826-6f87-4016-add9-5e6ff62fc6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Software']/parent::*</value>
      <webElementGuid>22e9afa7-5d83-4384-894d-d40622ba5984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[65]</value>
      <webElementGuid>f465d658-84b3-461a-b89f-552de97132d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/div/div/div[2]/div/div/div/div/span/a</value>
      <webElementGuid>fd7dc570-abc0-4e12-a8af-baba00bf01a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'NavigationLink_D_ListMyPegaLinksByLevel_pa1234149368512691pz.pxResults(3)_8' and (text() = 'Software' or . = 'Software')]</value>
      <webElementGuid>2d33c80a-4e47-4267-8ef2-df47a7e6da70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
